MRP-3901 tests: fix mds-survey.sh to support multiple MDTs
Partial porting of http://review.whamcloud.com/19437

This patch fixes mds-survey.sh and mds-survey to support
multiple MDTs.

Intel-bug-id: LU-4433
Signed-off-by: Fan Yong <fan.yong@intel.com>
Signed-off-by: Jian Yu <jian.yu@intel.com>
Change-Id: I9193b7fb65ab8b5dfd0817a8c203dae463deb090
Reviewed-by: Minh Diep <minh.diep@intel.com>
Reviewed-by: James Nunez <james.a.nunez@intel.com>
Reviewed-by: Oleg Drokin <oleg.drokin@intel.com>
Signed-off-by: Ashish Purkar <ashish.purkar@seagate.com>
Reviewed-on: http://es-gerrit.xyus.xyratex.com:8080/12509
Reviewed-by: Elena V. Gryaznova <elena.gryaznova@seagate.com>
Reviewed-by: Rahul Deshmukh <rahul.deshmukh@seagate.com>
Tested-by: Elena V. Gryaznova <elena.gryaznova@seagate.com>

diff --git a/lustre-iokit/mds-survey/mds-survey b/lustre-iokit/mds-survey/mds-survey
--- a/lustre-iokit/mds-survey/mds-survey
+++ b/lustre-iokit/mds-survey/mds-survey
@@ -58,31 +58,31 @@ basedir="tests"
 mdtbasedir="MDT%04x-"
 
 create_directories () {
-    local host=$1
-    local devno=$2
-    local ndir=$3
-    local rfile=$4
-    local mdtidx=$5
-    local idx
+	local host=$1
+	local devno=$2
+	local ndir=$3
+	local rfile=$4
+	local mdtidx=$5
+	local idx
 
-    for ((idx = 0; idx < $ndir; idx++)); do
-        if (( idx == 0 )); then
-            dirname="$(printf "${mdtbasedir}" $mdtidx)${basedir}"
-        else
-            dirname="$(printf "${mdtbasedir}" $mdtidx)${basedir}${idx}"
-        fi
-        remote_shell $host $lctl --device $devno test_mkdir /$dirname > $rfile 2>&1
-        while read line; do
-            echo "$line" | grep -q 'error: test_mkdir'
-            if [ $?  -eq 0 ]; then
-                cat $rfile >&2
-                echo "ERROR: fail test_mkdir" >&2
-                echo "ERROR"
-                return
-            fi
-        done < $rfile
-    done
-    echo $basedir
+	for ((idx = 0; idx < $ndir; idx++)); do
+		if (( idx == 0 )); then
+			dirname="$(printf "${mdtbasedir}" $mdtidx)${basedir}"
+		else
+			dirname="$(printf "${mdtbasedir}" $mdtidx)${basedir}${idx}"
+		fi
+		remote_shell $host $lctl --device $devno test_mkdir /$dirname > $rfile 2>&1
+		while read line; do
+			echo "$line" | grep -q 'error: test_mkdir'
+			if [ $?  -eq 0 ]; then
+				cat $rfile >&2
+				echo "ERROR: fail test_mkdir" >&2
+				echo "ERROR: fail test_mkdir"
+				return
+			fi
+		done < $rfile
+	done
+	echo $basedir
 }
 
 destroy_directories () {
@@ -252,19 +252,19 @@ print_summary "$(date) $0 from $(hostname)"
 # create directories
 tmpf="${workf}_tmp"
 for ((idx = 0; idx < $ndevs; idx++)); do
-    host=${host_names[$idx]}
-    devno=${devnos[$idx]}
-    client_name="${host}:${client_names[$idx]}"
-    mdtidx=${client_indexes[$idx]}
-    echo "=============> Create $dir_count directories on $client_name" >> $workf
-    destroy_directories $host $devno $dir_count $tmpf $mdtidx
-    ret=`create_directories $host $devno $dir_count $tmpf $mdtidx`
-    cat $tmpf >> $workf
-    rm $tmpf
-    if [ $ret = "ERROR" ]; then
-        print_summary "created directories on $client_name failed"
-        cleanup 1
-    fi
+	host=${host_names[$idx]}
+	devno=${devnos[$idx]}
+	client_name="${host}:${client_names[$idx]}"
+	mdtidx=${client_indexes[$idx]}
+	echo "=======> Create $dir_count directories on $client_name" >> $workf
+	destroy_directories $host $devno $dir_count $tmpf $mdtidx
+	ret=$(create_directories $host $devno $dir_count $tmpf $mdtidx)
+	cat $tmpf >> $workf
+	rm $tmpf
+	if [ $ret = "ERROR" ]; then
+		print_summary "created directories on $client_name failed"
+		cleanup 1
+	fi
 done
 
 snap=1
